# Gradle Specifications
org.gradle.jvmargs=-Xms256M -Xmx2G
org.gradle.daemon=false

# General Specifications
mc_version=1.7.10
mod_version=1.0.0a
forge_version=10.13.4.1614
mod_group=com.mof.fatcraft
mod_id=fatcraft
mod_name=Fatcraft
mod_archives_name=Fatcraft
mod_author=Fatih
mod_icon=TEM_logo.png
mod_description=Minecraft 2 but real.
mod_credits=
